controllers/ArchiveController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Devices;
use app\models\DevicesSearch;
use yii\helpers\ArrayHelper;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ArchiveController
 */
class ArchiveController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    // everything else is denied
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Devices models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DevicesSearch();
        $searchModel->load(Yii::$app->request->get());

        if($searchModel->id != null)
        {
            $model = $this->findModel($searchModel->id);
        } else {
            $model = null;
        }

        if($model != null)
        {
            $gasesArray = [];
            $data = $model->gasesValues;
            $createdAtArray = array_values(ArrayHelper::map($data, 'id', 'created_at'));

            $createdAtArray = array_filter($createdAtArray, function($created_at) use ($searchModel){
                if (($created_at > $searchModel->startDate) && ($created_at < $searchModel->endDate))
                {
                    return true;
                }

                return false;
            });

            $data = array_filter($data, function($gasValue) use ($searchModel){
                if (($gasValue->created_at > $searchModel->startDate) && ($gasValue->created_at < $searchModel->endDate))
                {
                    return true;
                }

                return false;
            });

            foreach ($searchModel->gases as $gas)
            {
                foreach ($data as $gasValue)
                {
                    if($gasValue->key == $gas)
                    {
                        if(isset($gasesArray[$gas]))
                        {
                            $gasesArray[$gas][$gasValue->created_at] = $gasValue->value;
                        } else
                        {
                            $gasesArray[$gas] = [$gasValue->created_at => $gasValue->value];
                        }
                    }
                }
            }
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'model' => $model,
            'createdAtArray' => isset($createdAtArray) ? $createdAtArray : null,
            'gasesArray' => isset($gasesArray) ? $gasesArray : null,
        ]);
    }

    /**
     * Finds the Devices model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Devices the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Devices::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Запрашиваемой страницы не существует.');
        }
    }
}

views/archive/_search.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\Devices */
/* @var $form yii\widgets\ActiveForm */

if($model->gases != null && !is_array($model->gases))
    $model->gases = explode(',', $model->gases);

?>

<div class="devices-form">

    <?php $form = ActiveForm::begin(['method' => 'get', 'id' => 'search-form']); ?>

    <div class="row">
            <div class="col-md-2">
                <?= $form->field($model, 'id')->dropDownList(\yii\helpers\ArrayHelper::map(\app\models\Devices::find()->all(), 'id', 'name'), [
                        'prompt' => 'Выберите устройство'
                ])->label('Устройство') ?>
            </div>

            <div class="col-md-3">
                <?= $form->field($model, 'gases')->widget(Select2::class, [
                    'options' => ['multiple' => true],
                ]) ?>
            </div>

            <div class="col-md-3">
                <?= $form->field($model, 'created_at_range')->widget(\kartik\daterange\DateRangePicker::class, [
                    'convertFormat' => true,
                    'pluginOptions' => [
                        'timePicker'=>true,
                        'timePickerIncrement'=>15,
                        'timePicker24Hour' => true,
                        'locale' => [
                            'format' => 'Y-m-d H:i:s',
                        ],
                        'ranges' => [
                            'Час назад' => ['moment().subtract(1, \'hours\')', 'moment()'],
                            'День назад' => ['moment().subtract(1, \'days\')', 'moment()'],
                            'Неделя назад' => ['moment().subtract(7, \'days\')', 'moment()'],
                            'Месяц назад' => ['moment().subtract(1, \'month\')', 'moment()'],
                        ],
                    ],
                ])->label('Дата') ?>
            </div>
    </div>

        <div class="form-group">
            <?= Html::tag( 'div','Готово', ['class' => 'btn btn-success', 'onclick' => '
              $("#search-form").attr("action", "'.\yii\helpers\Url::toRoute(['archive/index']).'").submit();
            ']) . Html::tag('div','<i class="fa fa-trash"></i> Очистить БД', ['class' => 'btn btn-danger pull-right', 'onclick' => '
              $("#search-form").attr("action", "'.\yii\helpers\Url::toRoute(['gases-values/truncate']).'").submit();
            ']) ?>
        </div>

    <?php ActiveForm::end(); ?>

</div>


<?php

$script = <<< JS
    $('#devicessearch-id').change(function()
    {
       var val = $(this).val();
       
       $.get('/devices/get-gases?id='+val, function(response){
             $('#devicessearch-gases').html('').trigger('change'); 
             $.each(response, function(i, key){
                  $('#devicessearch-gases').append(new Option(i, key, false, false)).trigger('change');
             });
       });
       
    });

    $('#devicessearch-id').trigger('change');

JS;

$this->registerJs($script, \yii\web\View::POS_READY);


?>

views/archive/index.php
<?php


?>

<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">Монитор</h4>
    </div>
    <div class="panel-body">

        <?= $this->render('_search', ['model' => $searchModel]) ?>

        <?php if($model != null && $gasesArray != null){ ?>

            <?= \app\widgets\Chart\Chart::widget([
                'id' => "chart",
                'data' => [
                    'y' => $gasesArray,
                    'x' => $createdAtArray
                ],
            ]) ?>

        <?php } else { ?>
            <hr>
            <p class="text-center">Данных не найдено</p>
            <hr>
        <?php } ?>
    </div>
</div>